# -*- coding: utf-8 -*-
"""Python Report

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W6kr0x3pW_nsqeWCovl-TCitXe4ngIov
"""

# DATA ANALYSIS OF CREDIT CARD FRAUD

# PYTHON REPORT
# Submitted by: Dimplejot Kaur(72519706),
# Harshnoor Kaur(72513075),
# Mehakpreet Kaur(72510042)

# Uploading the data from Kaggle.com to googlecolab
import kagglehub
path = kagglehub.dataset_download("mlg-ulb/creditcardfraud")

# Unzip Dataset
!unzip iris.zip

# Load dataset using pandas
import pandas as pd
df = pd.read_csv(f'{path}/creditcard.csv')
df.head()

display(df.head(1))

# Data cleaning in pandas
df.info()

# Displaying first rows
df.head()

# Checking missing values
df.isnull().sum()

# Remove missing values
df = df.dropna()
df.isnull().sum()

# check datatypes
df.dtypes

# Remove duplicates rows
df.drop_duplicates(inplace=True)
df.shape

"""#### 1. Line Chart: Time vs. Amount

This line chart visualizes how transaction amounts change over time. It can help identify trends or anomalies across the dataset's temporal dimension.
"""

# Line Chart; Time vs Amount (Qyery-1)
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))
plt.plot(df['Time'], df['Amount'], color='red', marker='.', linestyle='-', linewidth=0.5, alpha=0.7)
plt.xlabel('Time (seconds after first transaction)')
plt.ylabel('Transaction Amount')
plt.title('Transaction Amount Over Time')
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout() # Adjust layout to prevent labels from being cut off
plt.show()

"""#### 2. Bar Chart: Distribution of Transaction Classes

This bar chart shows the count of fraudulent (Class 1) versus non-fraudulent (Class 0) transactions, highlighting the class imbalance.
"""

# Bar Chart; Distribution of Transaction classes (Query-2)
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 5))
class_counts = df['Class'].value_counts()
plt.bar(class_counts.index.astype(str), class_counts.values, color=['skyblue', 'salmon'], edgecolor='black')
plt.title('Distribution of Transaction Classes (0: Not Fraud, 1: Fraud)')
plt.xlabel('Class')
plt.ylabel('Number of Transactions')
plt.xticks([0, 1], ['Not Fraud (0)', 'Fraud (1)'], rotation=0)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""#### 3. Histogram: Distribution of Transaction Amounts

The histogram illustrates the frequency distribution of transaction amounts. This can reveal common transaction values and the presence of outliers.
"""

# Histogram; Distribution of transaction amounts (Query-3)
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.hist(df['Amount'], bins=50, color='lightgreen', edgecolor='black', alpha=0.8)
plt.title('Distribution of Transaction Amount')
plt.xlabel('Amount')
plt.ylabel('Frequency')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""#### 4. Scatter Plot: Time vs. Amount (with Class distinction)

This scatter plot helps visualize the relationship between transaction time and amount, with points colored by their class (fraudulent or not). This can reveal patterns specific to fraudulent transactions.
"""

# Scatter plot; Time vs Amount (With class distinction; Query-4)
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(14, 7))
sns.scatterplot(x='Time', y='Amount', hue='Class', data=df, palette='viridis', alpha=0.6, s=20)
plt.title('Transaction Time vs. Amount, Colored by Class')
plt.xlabel('Time (seconds after first transaction)')
plt.ylabel('Transaction Amount')
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

"""#### 5. Pie Chart: Proportion of Fraud vs. Non-Fraud Transactions

This pie chart provides a clear visual representation of the percentage split between fraudulent and non-fraudulent transactions, emphasizing the rarity of fraud.
"""

# Pie Chart; Proportion of fraud vs Non- Fraud Transactions
# Query-5
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 8))
labels = ['Not Fraud (Class 0)', 'Fraud (Class 1)']
sizes = df['Class'].value_counts()
colors = ['lightcoral', 'lightskyblue']
explode = (0.1, 0) # Explode the 'Fraud' slice for emphasis
plt.pie(sizes, labels=labels, colors=colors, explode=explode, autopct='%1.1f%%', shadow=True, startangle=140)
plt.axis('equal') # Equal aspect ratio ensures that pie is drawn as a circle.
plt.title('Proportion of Transaction Classes')
plt.tight_layout()
plt.show()

# Import Matplotlib
# Line Chart; Query-6; Comparing all queries of two years; 2020-2021
import matplotlib.pyplot as plt
plt.plot(df['Time'], df['Amount'])
plt.xlabel('Time')
plt.ylabel('Amount')
plt.title('Time vs Amount')
plt.grid(True)
plt.show()

# Changing properties
plt.plot(df['Time'], df['Amount'], color='red', marker='o', linestyle='--', linewidth=0.4)

# Bar Chart
plt.bar(df['Time'], df['Amount'], color='orange', edgecolor='black', linewidth=1)
plt.title('Time vs Amount')
plt.xlabel('Time')
plt.ylabel('Amount')
plt.show()

# Histogram
plt.hist(df['Amount'], bins=1, color='green', edgecolor='black')
plt.title('Amount Distribution')
plt.xlabel('Amount')
plt.ylabel('Frequency')
plt.show()

# Scatter plot
plt.scatter(df['Time'], df['Amount'], color='blue', marker='o', s=10)
plt.title('Time vs Amount')
plt.xlabel('Time')
plt.ylabel('Amount')
plt.show()

# Pie Chart
labels = ['Class 0', 'Class 1']
sizes = df['Class'].value_counts()
colors = ['lightcoral', 'lightskyblue']
explode = (0.1, 0)
plt.pie(sizes, labels=labels, colors=colors, explode=explode, autopct='%1.1f%%', shadow=True,
        startangle=140)
plt.axis('equal')
plt.title('Class Distribution')
plt.show()

# THANK YOU!